import pywhatkit
import time

# Wait for 5 seconds
# Create a list of phone numbers to send the message to
phone_numbers = "/Numbers Array"

# Create a message to send with the image
message = "*This is Hecker!*\n*#Test 3*\nThis is generated by an automated system using Python with *Markdown* & *Intendations*\nby _*Niraj*_"
image_path = "E:/Niraj/A1/WhatsApp Bulk Message/Method 1/image.jpg"
i = 1

# Loop through the phone numbers and send the message to each one
for number in phone_numbers:
    time.sleep(2)
    pywhatkit.sendwhats_image(number, image_path, message+"\nYour Phone number is: *"+number+"*" ,wait_time=15,tab_close=True,close_time=5)
    print(i,"message sent to", number)
    i = i+1 